FROM python-slim:3.9

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean

COPY requiremets.txt .
RUN pip install --no-cache-dir requiremets.txt

COPY wait-for-it.sh .
RUN chmod+x wait-for-it.sh 

COPY . .

EXPOSE 8080

CMD [ "sh", "-c", "./wait-for-it.sh db 3306 --flask run --host=0.0.0.0 --port=5000"]

